const fs   = require('fs');
const path = require('path');

// __dirname = server/src/utils/ → ../../ = server/
let DATA_FILE = path.join(__dirname, '../../29062026_IGWF_Applicants_List.xlsx');

// Pre-built JSON cache (generated by scripts/prebuild.js at build time)
const CACHE_JSON = path.join(__dirname, '../../data/cache.json');

// ─── Mode flags ───────────────────────────────────────────────────────────────
let _mockMode = false;
let _apiMode  = false;
let _apiUrl   = '';

function setMockMode(enabled) { _mockMode = enabled; }
function setApiMode(enabled, url = '') { _apiMode = enabled; _apiUrl = url; }
function getMode() { return { mockMode: _mockMode, apiMode: _apiMode, apiUrl: _apiUrl }; }
function setDataFile(filePath) { DATA_FILE = filePath; }

const cache = {
  registered: [],
  drafts:     [],
  applied:    [],
  calling:    [],
  lastUpdated: null,
};

// ─── Columns we actually need (short names for fast lookup) ───────────────────
// All long column names get matched by partial key below
const NEEDED = [
  'ApplicationId','Application Type','AppliedBy','DraftDate','AppliedDate','Status',
  'FirstName','LastName','Email','PhoneNumber','DateOfBirth',
  'Gender','Gendernbsp',
  'WhatsappNumber','AadharCardNumber','Category',
  'IsArmyVeteranCategory','IsPWDCategory','IsMinority','Minority',
  'FamilyAnnualIncome',
  'Current_State','Current_District','Permanent_Region',
  'Employment_status',
  // Partial keys matched with startsWith below:
  'Do_you_have_a_valid_Indian_passport',
  'Do_you_have_a_laptop',
  'Height_in_cm',
  'Weight_in_kg',
  'BMI',
  'Do_you_wear_spectacles',
  'Any_known_chronic_medical_condition',
  'What_is_your_education_status',
  'Did_you_study_Physics_Mathematics_and_English',
  'Have_you_undergone_DGCA_medical_assessment',
  'Do_you_have_DGCA_computer_number',
  'Do_you_have_DGCA_Computer_Number',
  'How_did_you_hear_about',
  // Subject scores — matched by partial
  'What_was_your_score_in_Physics',
  'What_was_your_score_in_Maths',
  'What_was_your_score_in_English',
];

/**
 * Fast sheet reader: directly accesses cells by address for only the ~25 columns
 * we need. Avoids allocating 200-element arrays per row.
 */
function parseSheet(ws) {
  const XLSX = require('xlsx');
  const ref  = ws['!ref'];
  if (!ref) return [];

  const range = XLSX.utils.decode_range(ref);
  const encodeCell = XLSX.utils.encode_cell;

  // --- Read header row (only once) ---
  const headers = [];
  for (let c = range.s.c; c <= range.e.c; c++) {
    const cell = ws[encodeCell({ r: range.s.r, c })];
    headers.push(cell ? String(cell.v || '').trim() : '');
  }

  // --- Map needed column names → column indices ---
  const colMap = {}; // logicalName → colIndex
  headers.forEach((h, i) => {
    if (NEEDED.includes(h)) { colMap[h] = i; return; }
    for (const n of NEEDED) {
      if (colMap[n] === undefined && h.startsWith(n)) colMap[n] = i;
    }
    if (colMap['__phys'] === undefined && h.includes('score_in_Physics')) colMap['__phys'] = i;
    if (colMap['__math'] === undefined && h.includes('score_in_Maths'))   colMap['__math'] = i;
    if (colMap['__eng']  === undefined && h.includes('score_in_English'))  colMap['__eng']  = i;
  });

  const logicalNames = Object.keys(colMap);
  const colIndices   = logicalNames.map(k => colMap[k]);

  // --- Find ApplicationId column index for row filtering ---
  const appIdCol = colMap['ApplicationId'];
  if (appIdCol === undefined) return [];

  const rows = [];
  for (let r = range.s.r + 1; r <= range.e.r; r++) {
    // Skip row if ApplicationId is empty
    const idCell = ws[encodeCell({ r, c: appIdCol })];
    if (!idCell || !idCell.v) continue;

    const obj = {};
    for (let li = 0; li < logicalNames.length; li++) {
      const cell = ws[encodeCell({ r, c: colIndices[li] })];
      obj[logicalNames[li]] = cell ? String(cell.v ?? '').trim() : '';
    }
    rows.push(obj);
  }
  return rows;
}

function pickFirst(row, ...keys) {
  for (const key of keys) {
    // Exact key
    let val = row[key];
    // Partial match (for long column names stored under shortened key)
    if (!val || val === '' || val === '-') {
      const matchKey = Object.keys(row).find(k => k.startsWith(key) || key.startsWith(k));
      if (matchKey) val = row[matchKey];
    }
    if (val !== undefined && val !== null && String(val).trim() !== '' && String(val).trim() !== '-') {
      return String(val).trim();
    }
  }
  return null;
}

function normalizeDate(dateStr) {
  if (!dateStr) return null;
  const s = String(dateStr).trim();
  if (!s || s === '0') return null;

  // ISO format
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;

  // Excel serial date (e.g. 46199 = 2026-06-26)
  // Excel epoch: serial 1 = Jan 1 1900; Unix epoch = serial 25569
  if (/^\d{4,6}$/.test(s)) {
    const serial = parseInt(s, 10);
    if (serial > 30000 && serial < 60000) {
      const unixMs = (serial - 25569) * 86400 * 1000;
      const dt = new Date(unixMs);
      if (!isNaN(dt)) return dt.toISOString().split('T')[0];
    }
    return null; // don't fall through to new Date() for bare numbers
  }

  // DD/MM/YYYY or DD-MM-YYYY
  let m = s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);
  if (m) return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;

  const months = {jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};
  // DD-Mon-YY or DD-Mon-YYYY
  m = s.match(/(\d{1,2})[\-\s]([A-Za-z]{3})[\-\s](\d{2,4})/);
  if (m) {
    const yr = m[3].length === 2 ? '20' + m[3] : m[3];
    const mo = months[m[2].toLowerCase()];
    if (mo) return `${yr}-${String(mo).padStart(2,'0')}-${m[1].padStart(2,'0')}`;
  }
  // Mon DD, YYYY
  m = s.match(/([A-Za-z]{3})[\s](\d{1,2}),?\s*(\d{4})/);
  if (m) {
    const mo = months[m[1].toLowerCase()];
    if (mo) return `${m[3]}-${String(mo).padStart(2,'0')}-${m[2].padStart(2,'0')}`;
  }

  const dt = new Date(s);
  if (!isNaN(dt)) return dt.toISOString().split('T')[0];
  return null;
}

function parseRow(r) {
  const gender   = pickFirst(r,'Gendernbsp','Gender') || 'Not Specified';
  const state    = pickFirst(r,'Current_State') || 'Not Specified';
  const region   = pickFirst(r,'Permanent_Region') || 'Not Specified';
  const district = pickFirst(r,'Current_District') || 'Not Specified';
  const employment = pickFirst(r,'Employment_status') || 'Not Specified';

  let category = r['Category'] || 'General';
  if (!category || category === '-') category = 'General';

  const rawMed   = pickFirst(r,'Have_you_undergone_DGCA_medical_assessment') || '';
  const dgcaMedical  = ['Yes','No'].includes(rawMed) ? rawMed : 'No Data';
  const rawComp  = pickFirst(r,'Do_you_have_DGCA_computer_number','Do_you_have_DGCA_Computer_Number') || '';
  const dgcaComputer = ['Yes','No'].includes(rawComp) ? rawComp : 'No Data';

  const rawEdu = r['What_is_your_education_status'] || '';
  const educationStatus = rawEdu.length > 0 && rawEdu.length < 80 ? rawEdu : '';

  const rawInc = String(r['FamilyAnnualIncome'] || '');
  const familyIncome = rawInc !== '' && rawInc !== 'Not Specified' ? rawInc : 'Not Specified';

  const hasPassport = pickFirst(r,'Do_you_have_a_valid_Indian_passport') || 'No';
  const hasLaptop   = pickFirst(r,'Do_you_have_a_laptop') || 'No';

  const applicationType = r['Application Type'] || 'Draft';
  const dateField = r['DraftDate'] || r['AppliedDate'] || '';

  return {
    applicationId:     r['ApplicationId'] || '',
    applicationType,
    appliedBy:         r['AppliedBy'] || '',
    submittedDate:     normalizeDate(dateField),
    status:            r['Status'] || '',
    firstName:         (r['FirstName'] || '').trim(),
    lastName:          (r['LastName']  || '').trim(),
    name:              `${(r['FirstName']||'').trim()} ${(r['LastName']||'').trim()}`.trim(),
    email:             (r['Email'] || '').toLowerCase().trim(),
    phone:             String(r['PhoneNumber'] || ''),
    dateOfBirth:       r['DateOfBirth'] || '',
    gender:            gender === '-' ? 'Not Specified' : gender,
    category,
    currentState:      state    === '-' ? 'Not Specified' : state,
    currentDistrict:   district === '-' ? 'Not Specified' : district,
    permanentRegion:   region,
    familyAnnualIncome: rawInc,
    familyIncome,
    isArmyVeteran:     r['IsArmyVeteranCategory'] === 'Yes',
    isPWD:             r['IsPWDCategory'] === 'Yes',
    isMinority:        r['IsMinority'] === 'Yes',
    employmentStatus:  employment,
    hasPassport,
    hasLaptop,
    height:            pickFirst(r,'Height_in_cm') || '',
    weight:            pickFirst(r,'Weight_in_kg') || '',
    bmi:               r['BMI'] || '',
    wearSpectacles:    pickFirst(r,'Do_you_wear_spectacles') || '',
    chronicCondition:  pickFirst(r,'Any_known_chronic_medical_condition') || '',
    educationStatus,
    studiedPME:        pickFirst(r,'Did_you_study_Physics_Mathematics_and_English') || '',
    physicsScore:      r['__phys'] || '',
    mathsScore:        r['__math'] || '',
    englishScore:      r['__eng']  || '',
    dgcaMedical,
    dgcaComputer,
    heardAbout:        pickFirst(r,'How_did_you_hear_about') || 'Not Specified',
  };
}

function loadData() {
  // Fast path: load from pre-built JSON (Vercel deployment or after prebuild)
  if (fs.existsSync(CACHE_JSON)) {
    const t0 = Date.now();
    try {
      const data = JSON.parse(fs.readFileSync(CACHE_JSON, 'utf8'));
      cache.registered  = data.registered  || [];
      cache.drafts      = data.drafts      || [];
      cache.applied     = data.applied     || [];
      cache.calling     = data.calling     || [];
      cache.lastUpdated = data.lastUpdated || new Date().toISOString();
      const total = new Set([...cache.drafts.map(d=>d.applicationId),...cache.applied.map(a=>a.applicationId)]).size;
      console.log(`⚡ Loaded from cache.json in ${Date.now()-t0}ms — ${cache.registered.length} registered | ${cache.drafts.length} drafts | ${cache.applied.length} applied | ${total} unique`);
      return;
    } catch (e) {
      console.warn('⚠️  cache.json parse error, falling back to Excel:', e.message);
    }
  }

  // Slow path: parse Excel directly (local dev without prebuild)
  console.log('\n📂 Loading data from', path.basename(DATA_FILE), '...');
  if (!fs.existsSync(DATA_FILE)) {
    console.error('❌ Data file not found:', DATA_FILE);
    return;
  }

  const XLSX = require('xlsx');
  const t0   = Date.now();
  const wb   = XLSX.readFile(DATA_FILE, { cellDates: false });
  console.log(`   Sheets: ${wb.SheetNames.join(', ')} (read in ${Date.now()-t0}ms)`);

  // Draft Applicants
  const draftSheet = wb.Sheets['Draft Applicants'];
  if (draftSheet) {
    const t1 = Date.now();
    const rows = parseSheet(draftSheet);
    cache.drafts = rows.map(parseRow);
    console.log(`  ✅ Draft Applicants: ${cache.drafts.length} rows (${Date.now()-t1}ms)`);
  }

  // Applied Applicants
  const appliedSheet = wb.Sheets['Applied applicants'];
  if (appliedSheet) {
    const t1 = Date.now();
    const rows = parseSheet(appliedSheet);
    cache.applied = rows.map(parseRow);
    console.log(`  ✅ Applied applicants: ${cache.applied.length} rows (${Date.now()-t1}ms)`);
  }

  // Registered
  const regSheet = wb.Sheets['Registered Applicants'];
  if (regSheet) {
    const raw = XLSX.utils.sheet_to_json(regSheet, { defval: '' });
    cache.registered = raw.filter(r => r['Email'] || r['ID']).map(r => ({
      id:               String(r['ID'] || ''),
      uniqueId:         String(r['Unique ID'] || ''),
      firstName:        (r['First Name'] || '').trim(),
      lastName:         (r['Last Name']  || '').trim(),
      name:             `${(r['First Name']||'').trim()} ${(r['Last Name']||'').trim()}`.trim(),
      email:            (r['Email'] || '').toLowerCase().trim(),
      phone:            String(r['Phone Number'] || ''),
      registrationDate: normalizeDate(String(r['Registration Date'] || '')),
      createdAt:        String(r['Created At'] || ''),
    }));
    console.log(`  ✅ Registered: ${cache.registered.length} rows`);
  }

  // Calling Tracker — sheet headers are shifted by one column vs logical meaning
  // "Application Type" column actually holds ApplicationId values (e.g. SB-2026-0803)
  // "LastName" column holds firstName, "Email" holds lastName, etc.
  const callingSheet = wb.Sheets['Draft Applicants calling '] || wb.Sheets['Draft Applicants calling'];
  if (callingSheet) {
    const raw = XLSX.utils.sheet_to_json(callingSheet, { defval: '' });
    // __EMPTY is column A (applicationId). All other columns are shifted right by 1.
    cache.calling = raw.filter(r => {
      const v = String(r['__EMPTY'] || '').trim();
      return v.startsWith('SB-') || /^[A-Z]+-\d{4}-\d+$/.test(v);
    }).map(r => ({
      applicationId:  String(r['__EMPTY']        || '').trim(),
      applicationType: String(r['Application Type'] || '').trim(),
      firstName:      String(r['FirstName']      || '').trim(),
      lastName:       String(r['LastName']       || '').trim(),
      name:           `${String(r['FirstName']||'').trim()} ${String(r['LastName']||'').trim()}`.trim(),
      email:          String(r['Email']          || '').toLowerCase().trim(),
      phone:          String(r['PhoneNumber']    || ''),
      gender:         String(r['Gender']         || 'Not Specified').trim(),
      currentState:   String(r['Current_State']  || '').trim(),
      assignedMember: String(r['Assigned to']    || '').trim(),
      callStatus:     String(r['Calling Status'] || 'Not Called').trim(),
      queryStatus:    String(r['Call Status']    || '').trim(),
      issueCategory:  '',
      remark:         String(r['Remarks']        || '').trim(),
    }));
    console.log(`  ✅ Calling Tracker: ${cache.calling.length} rows`);
  }

  cache.lastUpdated = new Date().toISOString();
  const total = new Set([...cache.drafts.map(d=>d.applicationId), ...cache.applied.map(a=>a.applicationId)]).size;
  console.log(`  📊 ${cache.registered.length} registered | ${cache.drafts.length} drafts | ${cache.applied.length} applied | ${total} unique\n`);
}

function getCache() {
  if (_mockMode) return getMockCache();
  return cache;
}

// ─── Mock data generator ──────────────────────────────────────────────────────
const MOCK_STATES  = ['Tamil Nadu','Maharashtra','Karnataka','Telangana','Kerala','Gujarat','Rajasthan','Delhi','Uttar Pradesh','Andhra Pradesh','West Bengal','Punjab','Madhya Pradesh','Haryana','Bihar','Odisha','Assam','Chhattisgarh','Jharkhand','Uttarakhand'];
const MOCK_REGIONS = { 'Tamil Nadu':'Southern India','Maharashtra':'Western India','Karnataka':'Southern India','Telangana':'Southern India','Kerala':'Southern India','Gujarat':'Western India','Rajasthan':'Northern India','Delhi':'Northern India','Uttar Pradesh':'Northern India','Andhra Pradesh':'Southern India','West Bengal':'Eastern India','Punjab':'Northern India','Madhya Pradesh':'Central India','Haryana':'Northern India','Bihar':'Eastern India','Odisha':'Eastern India','Assam':'Northeast India','Chhattisgarh':'Central India','Jharkhand':'Eastern India','Uttarakhand':'Northern India' };
const MOCK_GENDERS = ['Female','Female','Female','Male','Not Specified'];
const MOCK_EMP    = ['Student','Student','Student','Unemployed','Employed'];
const MOCK_EDU    = ['12th Completed','Pursuing Graduation','Graduation Completed','Pursuing 12th'];
const MOCK_CAT    = ['General','General','General','OBC','SC','ST'];

function seededRand(seed) {
  let s = seed;
  return () => { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; };
}

function getMockCache() {
  const rand = seededRand(42);
  const pick = (arr) => arr[Math.floor(rand() * arr.length)];
  const total_r = 1200, total_d = 900, total_a = 500;

  const baseDate = new Date('2026-04-01');
  const days = 90;
  const mkDate = (i) => {
    const d = new Date(baseDate); d.setDate(d.getDate() + Math.floor(rand() * days));
    return d.toISOString().split('T')[0];
  };

  const makeApplicant = (i, type) => {
    const state = pick(MOCK_STATES);
    return {
      applicationId:    `SB-2026-M${String(i).padStart(4,'0')}`,
      applicationType:  type,
      firstName:        `Applicant`,
      lastName:         `${i}`,
      name:             `Applicant ${i}`,
      email:            `applicant${i}@demo.example`,
      phone:            '9999999999',
      dateOfBirth:      '2000-01-01',
      gender:           pick(MOCK_GENDERS),
      category:         pick(MOCK_CAT),
      currentState:     state,
      currentDistrict:  'District',
      permanentRegion:  MOCK_REGIONS[state] || 'Other',
      employmentStatus: pick(MOCK_EMP),
      familyAnnualIncome: pick(['Less than 1 Lakh','1-3 Lakhs','3-6 Lakhs','6-10 Lakhs']),
      educationStatus:  pick(MOCK_EDU),
      studiedPME:       pick(['Yes','Yes','No']),
      hasPassport:      pick(['Yes','Yes','No']),
      hasLaptop:        pick(['Yes','No']),
      dgcaMedical:      pick(['Yes','No','No Data']),
      dgcaComputer:     pick(['Yes','No','No Data']),
      wearSpectacles:   pick(['Yes','No']),
      chronicCondition: pick(['No','No','Yes']),
      height:           String(155 + Math.floor(rand() * 30)),
      weight:           String(45 + Math.floor(rand() * 35)),
      submittedDate:    mkDate(i),
      status:           type === 'Complete' ? 'Applied' : 'Draft',
    };
  };

  const registered = Array.from({ length: total_r }, (_, i) => ({
    id: String(i+1), uniqueId: `UID${i+1}`, firstName: 'Student', lastName: String(i+1),
    name: `Student ${i+1}`, email: `student${i+1}@demo.example`, phone: '9999999999',
    registrationDate: mkDate(i),
  }));
  const drafts  = Array.from({ length: total_d }, (_, i) => makeApplicant(i+1, 'Draft'));
  const applied = Array.from({ length: total_a }, (_, i) => makeApplicant(total_d+i+1, 'Complete'));

  return { registered, drafts, applied, calling: [], lastUpdated: new Date().toISOString() };
}

module.exports = { loadData, getCache, normalizeDate, setMockMode, setApiMode, getMode, setDataFile };
